# Variables para imagenes
path_isaui = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/isaui.png"
path_flecha = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/atras.png"
path_usuario = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/usuario.png"
path_facu = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/facu.png"
path_basura = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/basura.png"
path_check = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/check.png"
path_lapiz = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/lapiz.png"
path_lupa = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/lupa.png"
path_ojo = "C:/Preinscripcion_ISAUI/interfaz_grafica/media/ojo.png"
