# Variables para imagenes
path_isaui = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/isaui.png"
path_flecha = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/atras.png"
path_usuario = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/usuario.png"
path_facu = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/facu.png"
path_basura = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/iconos/basura.png"
path_check = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/iconos/check.png"
path_lapiz = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/iconos/lapiz.png"
path_lupa = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/iconos/lupa.png"
path_ojo = "C:/Users/benja/OneDrive/Desktop/Preinscripcion_ISAUI/interfaz_grafica/iconos/ojo.png"